Introduction aux méthodes de gradient

Méthodes d'optimisation pour des fonctions quadratiques

In [1]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Define the variables
n = 2

def A_n(n):
    if n == 0:
        return None
    elif n == 1:
        return np.array([[4]])
    elif n == 2:
        return np.array([[4, -2], [-2, 4]])
    elif n == 3:
        return np.array([[4, -2, 0], [-2, 4, -2], [0, -2, 4]])
    else:
        result = np.zeros((n, n))
        for i in range(n):
            for j in range(n):
                if i == j:
                    result[i, j] = 4
                elif i == j - 1 or i == j + 1:
                    result[i, j] = -2
        return result


def b_n(n):
    return np.ones((n, 1))


# Test the function
for n in range(1, 5):
    print(f"A_{n} = ")
    print(A_n(n))
    print(f"b_{n} = ")
    print(b_n(n))
    print()
    
n = 2

A_1 = 
[[4]]
b_1 = 
[[1.]]

A_2 = 
[[ 4 -2]
 [-2  4]]
b_2 = 
[[1.]
 [1.]]

A_3 = 
[[ 4 -2  0]
 [-2  4 -2]
 [ 0 -2  4]]
b_3 = 
[[1.]
 [1.]
 [1.]]

A_4 = 
[[ 4. -2.  0.  0.]
 [-2.  4. -2.  0.]
 [ 0. -2.  4. -2.]
 [ 0.  0. -2.  4.]]
b_4 = 
[[1.]
 [1.]
 [1.]
 [1.]]



In [9]:
# Now we define J_n and its gradient

def J_n(x, n):
    return 0.5 * np.dot(A_n(n) @ x, x) - np.dot(b_n(n).T, x).T

def grad_J_n(x, n):
    return A_n(n) @ x - b_n(n)

def grad_2_J_n(x, n):
    return A_n(n)

# Test the functions
x = np.array([[1], [1]])
print(f"J_{n} = {J_n(x, n)}")
print(f"grad_J_{n} = {grad_J_n(x, n)}")

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)